# Generated by Django 5.1.6 on 2025-02-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=100)),
                ('datastore', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=100)),
                ('vm_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
