# Generated by Django 5.1.6 on 2025-02-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmdeployment',
            name='cluster',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vmdeployment',
            name='datastore',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vmdeployment',
            name='network',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vmdeployment',
            name='template',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vmdeployment',
            name='vm_name',
            field=models.CharField(max_length=255),
        ),
    ]
