# Generated by Django 5.1.7 on 2025-07-03 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_vmactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vmdeployment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
